apiVersion: v0.1.0
envs:
- name: dev
  path: .xlr8s/envs/dev/env.yaml
git:
  repoUrl: git@github.com:XI2557-AnupFulzele/anup-project.git
  revision: main
name: anup-project-2534
vars:
  apps: null
  policy: null
